version: 2.1
jobs:
  run-test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.38.0-jammy

    # Steps to the job
    steps:
      - checkout
      - run:
          name: Download dependency
          environment:
            SECRET_KEY: SECRET_KEY 
          command: npm ci
      - run:
          name: Run tests
          command: npm run test
      - store_test_results:
          path: results.xml
      - run: hi deploy
      - jira/notify:
          job_type: deployment

# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test