name: Build and Test

on:
  push:
    branches:
      - master
      - develop

orbs:
  jira: circleci/jira@2.0.1  # Import the Jira orb
env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  run-test:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq

      - name: Download dependency
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Store test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: results.xml
      - jira/notify:
        job_type: deployment
        webhook_url: "https://128227a1-b1f0-4c2b-b7b6-1b32a1afee83.hello.atlassian-dev.net/x1/oOiqxcmRnfnh8SkFCTBUhS3rZyU"

    # Add your Jira notification steps here
